
[[CURRENCIES]]
code="GCP" 
issuer=" GCYBOLK5RKKLJU5KUTLS4YMZII57F5AK6PGH3M3DFE2U2IK5VRKWALHV "
name="Gold & Crypto "
desc="TOKEN FOR TEST"
image=" https://i.postimg.cc/qM1YcnPv/Screenshot-20260323-053057-Chrome.jpg)](https://postimg.cc/qzCj4tBP "
